[boris]
  version = 1

[build.dist-7-8]
  command = [
      ["master", "build", "dist-7-8", "-C", "mismi-core"]
    , ["master", "build", "dist-7-8", "-C", "mismi-autoscaling-core"]
    , ["master", "build", "dist-7-8", "-C", "mismi-autoscaling"]
    , ["master", "build", "dist-7-8", "-C", "mismi-cloudwatch"]
    , ["master", "build", "dist-7-8", "-C", "mismi-cloudwatch-logs"]
    , ["master", "build", "dist-7-8", "-C", "mismi-ec2-core"]
    , ["master", "build", "dist-7-8", "-C", "mismi-ec2"]
    , ["master", "build", "dist-7-8", "-C", "mismi-elb"]
    , ["master", "build", "dist-7-8", "-C", "mismi-emr"]
    , ["master", "build", "dist-7-8", "-C", "mismi-iam"]
    , ["master", "build", "dist-7-8", "-C", "mismi-rds-core"]
    , ["master", "build", "dist-7-8", "-C", "mismi-rds"]
    , ["master", "build", "dist-7-8", "-C", "mismi-s3-core"]
    , ["master", "build", "dist-7-8", "-C", "mismi-s3"]
    , ["master", "build", "dist-7-8", "-C", "mismi-sqs-core"]
    , ["master", "build", "dist-7-8", "-C", "mismi-sqs"]
    , ["master", "build", "dist-7-8", "-C", "mismi-sts"]
    , ["master", "build", "dist-7-8", "-C", "mismi-cli"]
    , ["master", "build", "dist-7-8", "-C", "mismi-openssl"]

    , ["bin/ci.cabal", "mismi-core"]
    , ["bin/ci.cabal", "mismi-ec2"]
    , ["bin/ci.cabal", "mismi-s3-core"]
    , ["bin/ci.cabal", "mismi-s3"]
    ]

[build.dist-7-10]
  command = [
      ["master", "build", "dist-7-10", "-C", "mismi-core"]
    , ["master", "build", "dist-7-10", "-C", "mismi-autoscaling-core"]
    , ["master", "build", "dist-7-10", "-C", "mismi-autoscaling"]
    , ["master", "build", "dist-7-10", "-C", "mismi-cloudwatch"]
    , ["master", "build", "dist-7-10", "-C", "mismi-cloudwatch-logs"]
    , ["master", "build", "dist-7-10", "-C", "mismi-ec2-core"]
    , ["master", "build", "dist-7-10", "-C", "mismi-ec2"]
    , ["master", "build", "dist-7-10", "-C", "mismi-elb"]
    , ["master", "build", "dist-7-10", "-C", "mismi-emr"]
    , ["master", "build", "dist-7-10", "-C", "mismi-iam"]
    , ["master", "build", "dist-7-10", "-C", "mismi-rds-core"]
    , ["master", "build", "dist-7-10", "-C", "mismi-rds"]
    , ["master", "build", "dist-7-10", "-C", "mismi-s3-core"]
    , ["master", "build", "dist-7-10", "-C", "mismi-s3"]
    , ["master", "build", "dist-7-10", "-C", "mismi-sqs-core"]
    , ["master", "build", "dist-7-10", "-C", "mismi-sqs"]
    , ["master", "build", "dist-7-10", "-C", "mismi-sts"]
    , ["master", "build", "dist-7-10", "-C", "mismi-cli"]
    , ["master", "build", "dist-7-10", "-C", "mismi-openssl"]

    , ["bin/ci.cabal", "mismi-core"]
    , ["bin/ci.cabal", "mismi-ec2"]
    , ["bin/ci.cabal", "mismi-s3-core"]
    , ["bin/ci.cabal", "mismi-s3"]
    ]

[build.dist-8-0]
  command = [
      ["master", "build", "dist-8-0", "-C", "mismi-core"]
    , ["master", "build", "dist-8-0", "-C", "mismi-autoscaling-core"]
    , ["master", "build", "dist-8-0", "-C", "mismi-autoscaling"]
    , ["master", "build", "dist-8-0", "-C", "mismi-cloudwatch"]
    , ["master", "build", "dist-8-0", "-C", "mismi-cloudwatch-logs"]
    , ["master", "build", "dist-8-0", "-C", "mismi-ec2-core"]
    , ["master", "build", "dist-8-0", "-C", "mismi-ec2"]
    , ["master", "build", "dist-8-0", "-C", "mismi-elb"]
    , ["master", "build", "dist-8-0", "-C", "mismi-emr"]
    , ["master", "build", "dist-8-0", "-C", "mismi-iam"]
    , ["master", "build", "dist-8-0", "-C", "mismi-rds-core"]
    , ["master", "build", "dist-8-0", "-C", "mismi-rds"]
    , ["master", "build", "dist-8-0", "-C", "mismi-s3-core"]
    , ["master", "build", "dist-8-0", "-C", "mismi-s3"]
    , ["master", "build", "dist-8-0", "-C", "mismi-sqs-core"]
    , ["master", "build", "dist-8-0", "-C", "mismi-sqs"]
    , ["master", "build", "dist-8-0", "-C", "mismi-sts"]
    , ["master", "build", "dist-8-0", "-C", "mismi-cli"]
    , ["master", "build", "dist-8-0", "-C", "mismi-openssl"]

    , ["bin/ci.cabal", "mismi-core"]
    , ["bin/ci.cabal", "mismi-ec2"]
    , ["bin/ci.cabal", "mismi-s3-core"]
    , ["bin/ci.cabal", "mismi-s3"]
    ]

[build.branches-7-8]
  command = [
      ["master", "build", "branches-7-8", "-C", "mismi-core"]
    , ["master", "build", "branches-7-8", "-C", "mismi-autoscaling-core"]
    , ["master", "build", "branches-7-8", "-C", "mismi-autoscaling"]
    , ["master", "build", "branches-7-8", "-C", "mismi-cloudwatch"]
    , ["master", "build", "branches-7-8", "-C", "mismi-cloudwatch-logs"]
    , ["master", "build", "branches-7-8", "-C", "mismi-ec2-core"]
    , ["master", "build", "branches-7-8", "-C", "mismi-ec2"]
    , ["master", "build", "branches-7-8", "-C", "mismi-elb"]
    , ["master", "build", "branches-7-8", "-C", "mismi-emr"]
    , ["master", "build", "branches-7-8", "-C", "mismi-iam"]
    , ["master", "build", "branches-7-8", "-C", "mismi-rds-core"]
    , ["master", "build", "branches-7-8", "-C", "mismi-rds"]
    , ["master", "build", "branches-7-8", "-C", "mismi-s3"]
    , ["master", "build", "branches-7-8", "-C", "mismi-s3-core"]
    , ["master", "build", "branches-7-8", "-C", "mismi-sqs-core"]
    , ["master", "build", "branches-7-8", "-C", "mismi-sqs"]
    , ["master", "build", "branches-7-8", "-C", "mismi-sts"]
    , ["master", "build", "branches-7-8", "-C", "mismi-cli"]
    , ["master", "build", "branches-7-8", "-C", "mismi-openssl"]


    , ["bin/ci.cabal", "mismi-core"]
    , ["bin/ci.cabal", "mismi-ec2"]
    , ["bin/ci.cabal", "mismi-s3-core"]
    , ["bin/ci.cabal", "mismi-s3"]
    ]

[build.branches-7-10]
  command = [
      ["master", "build", "branches-7-10", "-C", "mismi-core"]
    , ["master", "build", "branches-7-10", "-C", "mismi-autoscaling-core"]
    , ["master", "build", "branches-7-10", "-C", "mismi-autoscaling"]
    , ["master", "build", "branches-7-10", "-C", "mismi-cloudwatch"]
    , ["master", "build", "branches-7-10", "-C", "mismi-cloudwatch-logs"]
    , ["master", "build", "branches-7-10", "-C", "mismi-ec2-core"]
    , ["master", "build", "branches-7-10", "-C", "mismi-ec2"]
    , ["master", "build", "branches-7-10", "-C", "mismi-elb"]
    , ["master", "build", "branches-7-10", "-C", "mismi-emr"]
    , ["master", "build", "branches-7-10", "-C", "mismi-iam"]
    , ["master", "build", "branches-7-10", "-C", "mismi-rds-core"]
    , ["master", "build", "branches-7-10", "-C", "mismi-rds"]
    , ["master", "build", "branches-7-10", "-C", "mismi-s3-core"]
    , ["master", "build", "branches-7-10", "-C", "mismi-s3"]
    , ["master", "build", "branches-7-10", "-C", "mismi-sqs-core"]
    , ["master", "build", "branches-7-10", "-C", "mismi-sqs"]
    , ["master", "build", "branches-7-10", "-C", "mismi-sts"]
    , ["master", "build", "branches-7-10", "-C", "mismi-cli"]
    , ["master", "build", "branches-7-10", "-C", "mismi-openssl"]

    , ["bin/ci.cabal", "mismi-core"]
    , ["bin/ci.cabal", "mismi-ec2"]
    , ["bin/ci.cabal", "mismi-s3-core"]
    , ["bin/ci.cabal", "mismi-s3"]
    ]

[build.branches-8-0]
  command = [
      ["master", "build", "branches-8-0", "-C", "mismi-core"]
    , ["master", "build", "branches-8-0", "-C", "mismi-autoscaling-core"]
    , ["master", "build", "branches-8-0", "-C", "mismi-autoscaling"]
    , ["master", "build", "branches-8-0", "-C", "mismi-cloudwatch"]
    , ["master", "build", "branches-8-0", "-C", "mismi-cloudwatch-logs"]
    , ["master", "build", "branches-8-0", "-C", "mismi-ec2-core"]
    , ["master", "build", "branches-8-0", "-C", "mismi-ec2"]
    , ["master", "build", "branches-8-0", "-C", "mismi-elb"]
    , ["master", "build", "branches-8-0", "-C", "mismi-emr"]
    , ["master", "build", "branches-8-0", "-C", "mismi-iam"]
    , ["master", "build", "branches-8-0", "-C", "mismi-rds-core"]
    , ["master", "build", "branches-8-0", "-C", "mismi-rds"]
    , ["master", "build", "branches-8-0", "-C", "mismi-s3-core"]
    , ["master", "build", "branches-8-0", "-C", "mismi-s3"]
    , ["master", "build", "branches-8-0", "-C", "mismi-sqs-core"]
    , ["master", "build", "branches-8-0", "-C", "mismi-sqs"]
    , ["master", "build", "branches-8-0", "-C", "mismi-sts"]
    , ["master", "build", "branches-8-0", "-C", "mismi-cli"]
    , ["master", "build", "branches-8-0", "-C", "mismi-openssl"]

    , ["bin/ci.cabal", "mismi-core"]
    , ["bin/ci.cabal", "mismi-ec2"]
    , ["bin/ci.cabal", "mismi-s3-core"]
    , ["bin/ci.cabal", "mismi-s3"]
    ]

[build.reliability]
  command = [["bin/ci.reliability mismi-s3"]]

[build.validate]
  command = [["validate-respect"]]
