[boris]
  version = 1

[build.dist-7-10-kernel]
  command = [["master", "build", "dist-7-10", "-C", "mismi-kernel"]]
[build.dist-7-10-core]
  command = [["master", "build", "dist-7-10", "-C", "mismi-core"]]
[build.dist-7-10-autoscaling-core]
  command = [["master", "build", "dist-7-10", "-C", "mismi-autoscaling-core"]]
[build.dist-7-10-autoscaling]
  command = [["master", "build", "dist-7-10", "-C", "mismi-autoscaling"]]
[build.dist-7-10-cloudwatch]
  command = [["master", "build", "dist-7-10", "-C", "mismi-cloudwatch"]]
[build.dist-7-10-cloudwatch-logs]
  command = [["master", "build", "dist-7-10", "-C", "mismi-cloudwatch-logs"]]
[build.dist-7-10-ec2-core]
  command = [["master", "build", "dist-7-10", "-C", "mismi-ec2-core"]]
[build.dist-7-10-ec2]
  command = [["master", "build", "dist-7-10", "-C", "mismi-ec2"]]
[build.dist-7-10-elb]
  command = [["master", "build", "dist-7-10", "-C", "mismi-elb"]]
[build.dist-7-10-emr]
  command = [["master", "build", "dist-7-10", "-C", "mismi-emr"]]
[build.dist-7-10-iam]
  command = [["master", "build", "dist-7-10", "-C", "mismi-iam"]]
[build.dist-7-10-iam-core]
  command = [["master", "build", "dist-7-10", "-C", "mismi-iam-core"]]
[build.dist-7-10-rds-core]
  command = [["master", "build", "dist-7-10", "-C", "mismi-rds-core"]]
[build.dist-7-10-rds]
  command = [["master", "build", "dist-7-10", "-C", "mismi-rds"]]
[build.dist-7-10-s3-core]
  command = [["master", "build", "dist-7-10", "-C", "mismi-s3-core"]]
[build.dist-7-10-s3]
  command = [["master", "build", "dist-7-10", "-C", "mismi-s3"]]
[build.dist-7-10-sqs-core]
  command = [["master", "build", "dist-7-10", "-C", "mismi-sqs-core"]]
[build.dist-7-10-sqs]
  command = [["master", "build", "dist-7-10", "-C", "mismi-sqs"]]
[build.dist-7-10-sts]
  command = [["master", "build", "dist-7-10", "-C", "mismi-sts"]]
[build.dist-7-10-cli]
  command = [["master", "build", "dist-7-10", "-C", "mismi-cli"]]
[build.dist-7-10-openssl]
  command = [["master", "build", "dist-7-10", "-C", "mismi-openssl"]]

[build.dist-8-0-kernel]
  command = [["master", "build", "dist-8-0", "-C", "mismi-kernel"]]
[build.dist-8-0-core]
  command = [["master", "build", "dist-8-0", "-C", "mismi-core"]]
[build.dist-8-0-autoscaling-core]
  command = [["master", "build", "dist-8-0", "-C", "mismi-autoscaling-core"]]
[build.dist-8-0-autoscaling]
  command = [["master", "build", "dist-8-0", "-C", "mismi-autoscaling"]]
[build.dist-8-0-cloudwatch]
  command = [["master", "build", "dist-8-0", "-C", "mismi-cloudwatch"]]
[build.dist-8-0-cloudwatch-logs]
  command = [["master", "build", "dist-8-0", "-C", "mismi-cloudwatch-logs"]]
[build.dist-8-0-ec2-core]
  command = [["master", "build", "dist-8-0", "-C", "mismi-ec2-core"]]
[build.dist-8-0-ec2]
  command = [["master", "build", "dist-8-0", "-C", "mismi-ec2"]]
[build.dist-8-0-elb]
  command = [["master", "build", "dist-8-0", "-C", "mismi-elb"]]
[build.dist-8-0-emr]
  command = [["master", "build", "dist-8-0", "-C", "mismi-emr"]]
[build.dist-8-0-iam]
  command = [["master", "build", "dist-8-0", "-C", "mismi-iam"]]
[build.dist-8-0-iam-core]
  command = [["master", "build", "dist-8-0", "-C", "mismi-iam-core"]]
[build.dist-8-0-rds-core]
  command = [["master", "build", "dist-8-0", "-C", "mismi-rds-core"]]
[build.dist-8-0-rds]
  command = [["master", "build", "dist-8-0", "-C", "mismi-rds"]]
[build.dist-8-0-s3-core]
  command = [["master", "build", "dist-8-0", "-C", "mismi-s3-core"]]
[build.dist-8-0-s3]
  command = [["master", "build", "dist-8-0", "-C", "mismi-s3"]]
[build.dist-8-0-sqs-core]
  command = [["master", "build", "dist-8-0", "-C", "mismi-sqs-core"]]
[build.dist-8-0-sqs]
  command = [["master", "build", "dist-8-0", "-C", "mismi-sqs"]]
[build.dist-8-0-sts]
  command = [["master", "build", "dist-8-0", "-C", "mismi-sts"]]
[build.dist-8-0-cli]
  command = [["master", "build", "dist-8-0", "-C", "mismi-cli"]]
[build.dist-8-0-openssl]
  command = [["master", "build", "dist-8-0", "-C", "mismi-openssl"]]

[build.branches-7-10-kernel]
  command = [["master", "build", "branches-7-10", "-C", "mismi-kernel"]]
[build.branches-7-10-core]
  command = [["master", "build", "branches-7-10", "-C", "mismi-core"]]
[build.branches-7-10-autoscaling-core]
  command = [["master", "build", "branches-7-10", "-C", "mismi-autoscaling-core"]]
[build.branches-7-10-autoscaling]
  command = [["master", "build", "branches-7-10", "-C", "mismi-autoscaling"]]
[build.branches-7-10-cloudwatch]
  command = [["master", "build", "branches-7-10", "-C", "mismi-cloudwatch"]]
[build.branches-7-10-cloudwatch-logs]
  command = [["master", "build", "branches-7-10", "-C", "mismi-cloudwatch-logs"]]
[build.branches-7-10-ec2-core]
  command = [["master", "build", "branches-7-10", "-C", "mismi-ec2-core"]]
[build.branches-7-10-ec2]
  command = [["master", "build", "branches-7-10", "-C", "mismi-ec2"]]
[build.branches-7-10-elb]
  command = [["master", "build", "branches-7-10", "-C", "mismi-elb"]]
[build.branches-7-10-emr]
  command = [["master", "build", "branches-7-10", "-C", "mismi-emr"]]
[build.branches-7-10-iam]
  command = [["master", "build", "branches-7-10", "-C", "mismi-iam"]]
[build.branches-7-10-iam-core]
  command = [["master", "build", "branches-7-10", "-C", "mismi-iam-core"]]
[build.branches-7-10-rds-core]
  command = [["master", "build", "branches-7-10", "-C", "mismi-rds-core"]]
[build.branches-7-10-rds]
  command = [["master", "build", "branches-7-10", "-C", "mismi-rds"]]
[build.branches-7-10-s3-core]
  command = [["master", "build", "branches-7-10", "-C", "mismi-s3-core"]]
[build.branches-7-10-s3]
  command = [["master", "build", "branches-7-10", "-C", "mismi-s3"]]
[build.branches-7-10-sqs-core]
  command = [["master", "build", "branches-7-10", "-C", "mismi-sqs-core"]]
[build.branches-7-10-sqs]
  command = [["master", "build", "branches-7-10", "-C", "mismi-sqs"]]
[build.branches-7-10-sts]
  command = [["master", "build", "branches-7-10", "-C", "mismi-sts"]]
[build.branches-7-10-cli]
  command = [["master", "build", "branches-7-10", "-C", "mismi-cli"]]
[build.branches-7-10-openssl]
  command = [["master", "build", "branches-7-10", "-C", "mismi-openssl"]]

[build.branches-8-0-kernel]
  command = [["master", "build", "branches-8-0", "-C", "mismi-kernel"]]
[build.branches-8-0-core]
  command = [["master", "build", "branches-8-0", "-C", "mismi-core"]]
[build.branches-8-0-autoscaling-core]
  command = [["master", "build", "branches-8-0", "-C", "mismi-autoscaling-core"]]
[build.branches-8-0-autoscaling]
  command = [["master", "build", "branches-8-0", "-C", "mismi-autoscaling"]]
[build.branches-8-0-cloudwatch]
  command = [["master", "build", "branches-8-0", "-C", "mismi-cloudwatch"]]
[build.branches-8-0-cloudwatch-logs]
  command = [["master", "build", "branches-8-0", "-C", "mismi-cloudwatch-logs"]]
[build.branches-8-0-ec2-core]
  command = [["master", "build", "branches-8-0", "-C", "mismi-ec2-core"]]
[build.branches-8-0-ec2]
  command = [["master", "build", "branches-8-0", "-C", "mismi-ec2"]]
[build.branches-8-0-elb]
  command = [["master", "build", "branches-8-0", "-C", "mismi-elb"]]
[build.branches-8-0-emr]
  command = [["master", "build", "branches-8-0", "-C", "mismi-emr"]]
[build.branches-8-0-iam]
  command = [["master", "build", "branches-8-0", "-C", "mismi-iam"]]
[build.branches-8-0-iam-core]
  command = [["master", "build", "branches-8-0", "-C", "mismi-iam-core"]]
[build.branches-8-0-rds-core]
  command = [["master", "build", "branches-8-0", "-C", "mismi-rds-core"]]
[build.branches-8-0-rds]
  command = [["master", "build", "branches-8-0", "-C", "mismi-rds"]]
[build.branches-8-0-s3-core]
  command = [["master", "build", "branches-8-0", "-C", "mismi-s3-core"]]
[build.branches-8-0-s3]
  command = [["master", "build", "branches-8-0", "-C", "mismi-s3"]]
[build.branches-8-0-sqs-core]
  command = [["master", "build", "branches-8-0", "-C", "mismi-sqs-core"]]
[build.branches-8-0-sqs]
  command = [["master", "build", "branches-8-0", "-C", "mismi-sqs"]]
[build.branches-8-0-sts]
  command = [["master", "build", "branches-8-0", "-C", "mismi-sts"]]
[build.branches-8-0-cli]
  command = [["master", "build", "branches-8-0", "-C", "mismi-cli"]]
[build.branches-8-0-openssl]
  command = [["master", "build", "branches-8-0", "-C", "mismi-openssl"]]

[build.dist-7-10-kernel-cabal-test]
  command = [["master", "build", "dist-7-10-cabal-test", "-C", "mismi-kernel"]]
[build.dist-7-10-core-cabal-test]
  command = [["master", "build", "dist-7-10-cabal-test", "-C", "mismi-core"]]
[build.dist-7-10-ec2-core-cabal-test]
  command = [["master", "build", "dist-7-10-cabal-test", "-C", "mismi-ec2-core"]]
[build.dist-7-10-autoscalingcabal-test]
  command = [["master", "build", "dist-7-10-cabal-test", "-C", "mismi-autoscaling"]]
[build.dist-7-10-autoscaling-core-cabal-test]
  command = [["master", "build", "dist-7-10-cabal-test", "-C", "mismi-autoscaling-core"]]
[build.dist-7-10-s3-core-cabal-test]
  command = [["master", "build", "dist-7-10-cabal-test", "-C", "mismi-s3-core"]]
[build.dist-7-10-s3-cabal-test]
  command = [["master", "build", "dist-7-10-cabal-test", "-C", "mismi-s3"]]
[build.dist-7-10-sqs-core-cabal-test]
  command = [["master", "build", "dist-7-10-cabal-test", "-C", "mismi-sqs-core"]]
[build.dist-7-10-sqs-cabal-test]
  command = [["master", "build", "dist-7-10-cabal-test", "-C", "mismi-sqs"]]

[build.branches-7-10-kernel-cabal-test]
  command = [["master", "build", "branches-7-10-cabal-test", "-C", "mismi-kernel"]]
[build.branches-7-10-core-cabal-test]
  command = [["master", "build", "branches-7-10-cabal-test", "-C", "mismi-core"]]
[build.branches-7-10-ec2-core-cabal-test]
  command = [["master", "build", "branches-7-10-cabal-test", "-C", "mismi-ec2-core"]]
[build.branches-7-10-autoscaling-cabal-test]
  command = [["master", "build", "branches-7-10-cabal-test", "-C", "mismi-autoscaling"]]
[build.branches-7-10-autoscaling-core-cabal-test]
  command = [["master", "build", "branches-7-10-cabal-test", "-C", "mismi-autoscaling-core"]]
[build.branches-7-10-s3-core-cabal-test]
  command = [["master", "build", "branches-7-10-cabal-test", "-C", "mismi-s3-core"]]
[build.branches-7-10-s3-cabal-test]
  command = [["master", "build", "branches-7-10-cabal-test", "-C", "mismi-s3"]]
[build.branches-7-10-sqs-core-cabal-test]
  command = [["master", "build", "branches-7-10-cabal-test", "-C", "mismi-sqs-core"]]
[build.branches-7-10-sqs-cabal-test]
  command = [["master", "build", "branches-7-10-cabal-test", "-C", "mismi-sqs"]]

[build.dist-reliability]
  command = [["bin/ci.reliability mismi-s3"]]

[build.dist-validate]
  command = [["validate-respect"]]

[build.all-submodules]
  command = [["dangling-refs"]]

[build.all-rebased]
  command = [["rebased"]]
