[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20181122052716-977567b/master-haskell-20181122052716-977567b"
  version = 1
sha1 = "b5434adb04dd0f7dee53b030f3c4cf1fed941c66"

[global]
  CACHE = "false"

[build.dist]
  GHC_VERSION="7.10.2"
  CABAL_VERSION = "1.24.0.0"

[build.dist-7-10]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"

[build.branches-7-10]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"

[build.dist-8-0]
  GHC_VERSION = "8.0.2"
  CABAL_VERSION = "1.24.0.2"

[build.branches-8-0]
  GHC_VERSION = "8.0.2"
  CABAL_VERSION = "1.24.0.2"

[build.dist-7-10-cabal-test]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"
  TEST = "false"
  CABAL_TEST = "true"

[build.branches-7-10-cabal-test]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.0"
  TEST = "false"
  CABAL_TEST = "true"

[build.dist-8-0-cabal-test]
  GHC_VERSION = "8.0.2"
  CABAL_VERSION = "1.24.0.2"
  TEST = "false"
  CABAL_TEST = "true"

[build.branches-8-0-cabal-test]
  GHC_VERSION = "8.0.2"
  CABAL_VERSION = "1.24.0.2"
  TEST = "false"
  CABAL_TEST = "true"
