[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20190117000143-201595f/master-haskell-20190117000143-201595f"
  version = 1
  sha1 = "3ba53248015b00824f90ca497b5d3bcce5699608"

[global]
  CACHE = "true"

[build.dist-7-10]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.2"

[build.branches-7-10]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.24.0.2"

[build.dist-8-0]
  GHC_VERSION = "8.0.2"
  CABAL_VERSION = "1.24.0.2"

[build.branches-8-0]
  GHC_VERSION = "8.0.2"
  CABAL_VERSION = "1.24.0.2"
