[master]
  version = 1
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20160623072912-ccea728/master-haskell-20160623072912-ccea728"
  sha1 = "e150d58a710c500eb908db492b3dcd0e532b2725"

[build.dist]
  GHC_VERSION="7.10.2"
  CABAL_VERSION = "1.22.4.0"

[build.dist-7-10]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"

[build.branches-7-10]
  # Change these once fully switched to boris
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"

[build.dist-8-0]
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"

[build.branches-8-0]
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"

[build.dist-7-10-cabal-test]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  TEST = "false"
  CABAL_TEST = "true"

[build.branches-7-10-cabal-test]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  TEST = "false"
  CABAL_TEST = "true"
